#!/usr/bin/env node

/**
 * MedAI Setup Wizard
 * Helps configure local environment after Vercel-Supabase integration
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('\n🚀 ============================================');
console.log('   MedAI Setup Wizard');
console.log('   ============================================\n');

console.log('✅ You\'ve integrated Vercel with Supabase!\n');
console.log('Now let\'s configure your LOCAL development environment.\n');

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function setup() {
  console.log('📋 Please get your Supabase credentials:\n');
  console.log('Option 1: From Vercel Dashboard');
  console.log('  → https://vercel.com/dashboard');
  console.log('  → Your Project → Settings → Environment Variables');
  console.log('  → Copy VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY\n');
  
  console.log('Option 2: From Supabase Dashboard');
  console.log('  → https://app.supabase.com/');
  console.log('  → Your Project → Settings → API');
  console.log('  → Copy Project URL and anon/public key\n');
  
  console.log('─────────────────────────────────────────────\n');

  const supabaseUrl = await question('Enter VITE_SUPABASE_URL: ');
  const supabaseKey = await question('Enter VITE_SUPABASE_ANON_KEY: ');

  if (!supabaseUrl || !supabaseKey) {
    console.log('\n❌ Both values are required!');
    rl.close();
    process.exit(1);
  }

  // Validate URL format
  if (!supabaseUrl.startsWith('https://') || !supabaseUrl.includes('.supabase.co')) {
    console.log('\n⚠️  Warning: URL format looks incorrect.');
    console.log('   Expected format: https://xxxxx.supabase.co');
    const proceed = await question('   Continue anyway? (y/n): ');
    if (proceed.toLowerCase() !== 'y') {
      rl.close();
      process.exit(0);
    }
  }

  // Create .env file
  const envContent = `# =====================================================
# MedAI - Frontend Environment Variables
# =====================================================
# Auto-generated by setup wizard
# Last updated: ${new Date().toISOString()}
# =====================================================

# =====================================================
# SUPABASE CONFIGURATION (Required)
# =====================================================
VITE_SUPABASE_URL=${supabaseUrl}
VITE_SUPABASE_ANON_KEY=${supabaseKey}

# =====================================================
# BACKEND API (Optional - for module features)
# =====================================================
VITE_API_BASE_URL=http://localhost:5000/api
VITE_SEARCH_SERVICE_URL=http://localhost:5000

# =====================================================
# GOOGLE MAPS API (Optional)
# =====================================================
# Get from: https://console.cloud.google.com/apis/credentials
# VITE_GOOGLE_MAPS_API_KEY=your-google-maps-api-key

# =====================================================
# ENCRYPTION & SECURITY (Optional)
# =====================================================
# Generate with: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
# VITE_ENCRYPTION_MASTER_KEY=your-64-character-encryption-key
# VITE_AADHAAR_HMAC_SECRET=your-64-character-hmac-secret

# =====================================================
# DEVELOPMENT
# =====================================================
NODE_ENV=development
`;

  const envPath = path.join(process.cwd(), '.env');
  fs.writeFileSync(envPath, envContent);

  console.log('\n✅ .env file created successfully!\n');
  console.log('📄 File location:', envPath);
  console.log('\n🎯 Next Steps:\n');
  console.log('1. Run: npm run dev');
  console.log('2. Go to: http://localhost:5173/auth');
  console.log('3. Test signup/login\n');
  console.log('🔒 IMPORTANT: Never commit .env to git!\n');
  
  rl.close();
}

setup().catch(error => {
  console.error('\n❌ Setup failed:', error.message);
  rl.close();
  process.exit(1);
});
